name: unison-codebase-sqlite
github: unisonweb/unison

library:
  source-dirs: .

extra-source-files:
  - sql/*

dependencies:
  - base
  - bytes
  - bytestring
  - containers
  - extra
  - here
  - lens
  - monad-validate
  - mtl
  - safe
  - sqlite-simple
  - text
  - transformers
  - unliftio
  - vector
  - unison-codebase
  - unison-codebase-sync
  - unison-core
  - unison-prelude
  - unison-util
  - unison-util-serialization
  - unison-util-term
