name: unison-util
github: unisonweb/unison

library:
  source-dirs: src
  when:
    - condition: false
      other-modules: Paths_unison_util

benchmarks:
  bench:
    when:
      - condition: false
        other-modules: Paths_unison_util
    dependencies:
      - criterion
      - sandi
      - unison-util
      - unison-util-base32hex
    main: Main.hs
    source-dirs: bench

dependencies:
  - base
  - base32
  - bytestring
  - containers
  - cryptonite
  - extra
  - lens
  - memory
  - safe
  - text
  - time
  - unison-prelude
  - unison-util-relation
  - unliftio
  - vector

default-extensions:
  - ApplicativeDo
  - BlockArguments
  - DeriveFunctor
  - DerivingStrategies
  - DoAndIfThenElse
  - FlexibleContexts
  - FlexibleInstances
  - LambdaCase
  - MultiParamTypeClasses
  - NamedFieldPuns
  - OverloadedStrings
  - PatternSynonyms
  - ScopedTypeVariables
  - TupleSections
  - TypeApplications
