name: unison-util
github: unisonweb/unison

library:
  source-dirs: .

dependencies:
  - base
  - bytestring
  - containers
  - cryptonite
  - deepseq
  - lens
  - memory
  - safe
  - sandi
  - text
  - time
  - unliftio

default-extensions:
  - ApplicativeDo
  - BlockArguments
  - DeriveFunctor
  - DerivingStrategies
  - DoAndIfThenElse
  - FlexibleContexts
  - FlexibleInstances
  - LambdaCase
  - MultiParamTypeClasses
  - ScopedTypeVariables
  - TupleSections
  - TypeApplications
