name: unison-util
github: unisonweb/unison

library:
  source-dirs: .

dependencies:
  - base
  - bytestring
  - containers
  - cryptonite
  - lens
  - memory
  - safe
  - sandi
  - text
  - time
  - unison-util-relation
  - unliftio
