name: unison-codebase-server
github: unisonweb/unison
copyright: Copyright (C) 2013-2021 Unison Computing, PBC and contributors

library:
  source-dirs: src
  ghc-options: -Wall -fno-warn-name-shadowing -fno-warn-missing-pattern-synonym-signatures -funbox-strict-fields
  dependencies:
    - base
    - unison-util-relation
    - unison-core1
    - containers
    - unison-prelude
    - unison-parser-typechecker

default-extensions:
  - ApplicativeDo
  - BlockArguments
  - DeriveFunctor
  - DerivingStrategies
  - DoAndIfThenElse
  - FlexibleContexts
  - FlexibleInstances
  - LambdaCase
  - MultiParamTypeClasses
  - ScopedTypeVariables
  - TupleSections
  - TypeApplications

flags:
  optimized:
    manual: true
    default: false

when:
  - condition: flag(optimized)
    ghc-options: -O2 -funbox-strict-fields
