name: unison-codebase-server
github: unisonweb/unison
copyright: Copyright (C) 2013-2021 Unison Computing, PBC and contributors

library:
  source-dirs: src
  ghc-options: -Wall -fno-warn-name-shadowing -fno-warn-missing-pattern-synonym-signatures -funbox-strict-fields
  dependencies:
    - base
    - unison-util-relation
    - unison-core1
    - containers
    - unison-prelude
    - unison-parser-typechecker
    - aeson
    - openapi3
    - text
    - transformers
    - mtl
    - servant
    - bytestring
    - fuzzyfind
    - extra
    - lens
    - errors
    - servant-server
    - servant-openapi3
    - servant-docs
    - mwc-random
    - filepath
    - directory
    - wai
    - NanoID
    - utf8-string
    - uri-encode
    - async
    - warp
    - http-types
    - http-media

default-extensions:
  - ApplicativeDo
  - BlockArguments
  - DeriveFunctor
  - DerivingStrategies
  - DoAndIfThenElse
  - FlexibleContexts
  - FlexibleInstances
  - LambdaCase
  - MultiParamTypeClasses
  - ScopedTypeVariables
  - TupleSections
  - TypeApplications

flags:
  optimized:
    manual: true
    default: false

when:
  - condition: flag(optimized)
    ghc-options: -O2 -funbox-strict-fields
