name: unison-util-hashable-v1-impl
github: unisonweb/unison

library:
  source-dirs: .

dependencies:
  - base
  - unison-util-hash
  - unison-util-hashable-v1
  - bytestring
  - containers
  - cryptonite
  - lens
  - memory
  - safe
  - sandi
  - text
  - time
  - unliftio
  - unison-util-base32hex
