name: "release"

on:
  push:
    tags:
      - "release/*"

jobs:
  release:
    name: "release"
    runs-on: "ubuntu-latest"

    strategy:
      # Run each build to completion, regardless of if any have failed
      fail-fast: false
    steps:
      - name: create-release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
        with:
          if-no-files-found: error
          name: build-linux
          path: ucm-linux.tar.gz
  
  release:
    name: "create_release"
    runs-on: "ubuntu-latest"
    needs:
      - build_linux
      - build_macos

    steps:
      - uses: actions/checkout@v2
      - name: echo upload_url
        run: "echo ${{ steps.create_release.outputs.upload_url }}"

      - name: make download dir
        run: "mkdir /tmp/ucm"

      - name: "download artifacts"
        uses: actions/download-artifact@v2
        with:
          path: /tmp/ucm

      - name: "see what we got"
        run: "ls -R /tmp/ucm"

      - name: make a release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: /tmp/ucm/**/*.tar.gz

